name: Messaging app tests


# Triggers: on push, PR, or manual run (with optional tag input)
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Select Playwright tag to run'
        required: false
        default: ''
        type: choice
        options:
          - ''
          - smoke
          - regression
          - sanity
          - critical

jobs:
  messaging-app-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Clean old Playwright report
        run: rm -rf playwright-report
      # Run Playwright tests, optionally filtering by tag if provided
      - name: Run Playwright tests
        run: |
          if [ -n "${{ github.event.inputs.tag }}" ]; then
            echo "Running tests with tag: ${{ github.event.inputs.tag }}"
            npx playwright test --grep @${{ github.event.inputs.tag }} --reporter=html
          else
            npx playwright test --reporter=html
          fi
      - name: List Playwright report contents
        if: always()
        run: |
          echo "Listing Playwright report folder contents before moving:"
          ls -l playwright-report

      # Archive the Playwright report with the run ID for uniqueness
      - name: Archive Playwright report with run ID
        if: always()
        run: |
          mkdir -p archived-reports/${{ github.run_id }}
          cp -r playwright-report/* archived-reports/${{ github.run_id }}/

      - name: Prepare report for GitHub Pages
        if: always()
        run: |
          rm -rf gh-pages
          mkdir -p gh-pages
          mv playwright-report/* gh-pages/

      - name: Upload HTML report to GitHub Pages  
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gh-pages
          publish_branch: gh-pages

      # Upload the uniquely archived Playwright HTML report as an artifact
      - name: Upload Playwright HTML report as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ github.run_id }}
          path: archived-reports/${{ github.run_id }}

      - name: Add GitHub Pages report link to summary
        if: always()
        run: echo "[View Playwright HTML Report](https://liubomyrpodoliak.github.io/messaging-app/)" >> $GITHUB_STEP_SUMMARY
