name: Playwright Tests and Publish Report

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Start static server
        run: npm run start &
      - name: Wait for server to be ready
        run: npx wait-on http://localhost:5000/dummy-messaging-app.html
      - name: Run Playwright tests
        run: npx playwright test --reporter=html
      - name: Prepare report for GitHub Pages
        run: |
          rm -rf gh-pages
          mv playwright-report gh-pages
      - name: Upload HTML report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gh-pages
          publish_branch: gh-pages
      - name: Upload Playwright HTML report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: gh-pages
      - name: Show GitHub Pages report link
        run: |
          echo "Report: https://liubomyrpodoliak.github.io/messaging-app/"
